### ISSUE TITLE
Automatically delete head branches

### ISSUE THREAD

**Issue by javierm** [code4romania/consul#47]
Hi, @decembrya :smile:.

In order to make it easier to keep track of the active branches and have less messages saying "you can now delete this branch", would it be possible to activate the "automatically delete head branches" option in the repository settings? Like this:

![Repo settings, with a checked "automatically delete head branches" checkbox](https://user-images.githubusercontent.com/35156/158829732-0cb9e64f-5ca5-49fb-bfc1-9c587be16722.png)

Thanks!

**Comment by decembrya** [comment]
Will be happy to do this once github is fully functional again :( https://www.githubstatus.com/

**Comment by decembrya** [comment]
Done!
